// Commission rule: inverse relationship with average check
// Expensive (>1M VND): 3–4% | Medium (300K–1M): 5–6% | Cheap (<300K): 7%
// Distribution: 50% platform | 25% business referrer | 15% user referrer | 10% gamification pool

export const VERTICALS_CONFIG = [
  {
    id: 1,
    slug: 'housing',
    emoji: '🏠',
    name: { ru: 'Жильё', en: 'Housing', vi: 'Nhà ở' },
    commissionPct: 3,
    userDiscountPct: 2,
    bloggerReferralPct: 2,
    avgCheckVnd: 5000000,
    subgroups: [
      { slug: 'apartments',  name: { ru: 'Аренда квартир', en: 'Apartment Rental', vi: 'Thuê căn hộ' } },
      { slug: 'villas',      name: { ru: 'Виллы', en: 'Villas', vi: 'Biệt thự' } },
      { slug: 'buying',      name: { ru: 'Покупка', en: 'Buying', vi: 'Mua bán' } },
      { slug: 'hostels',     name: { ru: 'Хостелы', en: 'Hostels', vi: 'Nhà nghỉ' } },
      { slug: 'guesthouses', name: { ru: 'Гестхаусы', en: 'Guesthouses', vi: 'Guesthouse' } },
      { slug: 'hotels',      name: { ru: 'Отели', en: 'Hotels', vi: 'Khách sạn' } },
    ],
  },
  {
    id: 2,
    slug: 'transport',
    emoji: '🏍',
    name: { ru: 'Транспорт', en: 'Transport', vi: 'Giao thông' },
    commissionPct: 5,
    userDiscountPct: 4,
    bloggerReferralPct: 3,
    avgCheckVnd: 300000,
    subgroups: [
      { slug: 'motorbikes',     name: { ru: 'Байки', en: 'Motorbikes', vi: 'Xe máy' } },
      { slug: 'cars',           name: { ru: 'Авто', en: 'Cars', vi: 'Ô tô' } },
      { slug: 'transfer',       name: { ru: 'Трансфер', en: 'Transfer', vi: 'Đưa đón' } },
      { slug: 'moto-repair',    name: { ru: 'Ремонт байков', en: 'Moto Repair', vi: 'Sửa xe máy' } },
      { slug: 'car-repair',     name: { ru: 'Ремонт авто', en: 'Car Repair', vi: 'Sửa ô tô' } },
      { slug: 'driving-school', name: { ru: 'Права', en: 'Driving School', vi: 'Lái xe' } },
    ],
  },
  {
    id: 3,
    slug: 'food',
    emoji: '🍜',
    name: { ru: 'Еда', en: 'Food', vi: 'Ăn uống' },
    commissionPct: 7,
    userDiscountPct: 5,
    bloggerReferralPct: 4,
    avgCheckVnd: 200000,
    subgroups: [
      { slug: 'restaurants', name: { ru: 'Рестораны', en: 'Restaurants', vi: 'Nhà hàng' } },
      { slug: 'cafes',       name: { ru: 'Кафе', en: 'Cafes', vi: 'Quán ăn' } },
      { slug: 'coffee',      name: { ru: 'Кофейни', en: 'Coffee Shops', vi: 'Cà phê' } },
      { slug: 'delivery',    name: { ru: 'Доставка', en: 'Delivery', vi: 'Giao đồ ăn' } },
      { slug: 'street-food', name: { ru: 'Стрит-фуд', en: 'Street Food', vi: 'Đồ ăn đường phố' } },
      { slug: 'bakeries',    name: { ru: 'Пекарни', en: 'Bakeries', vi: 'Tiệm bánh' } },
      { slug: 'vegan',       name: { ru: 'Веган', en: 'Vegan', vi: 'Đồ ăn chay' } },
      { slug: 'bars',        name: { ru: 'Бары', en: 'Bars', vi: 'Quán bar' } },
    ],
  },
  {
    id: 4,
    slug: 'tours',
    emoji: '🏖',
    name: { ru: 'Туры', en: 'Tours', vi: 'Tour du lịch' },
    commissionPct: 5,
    userDiscountPct: 4,
    bloggerReferralPct: 3,
    avgCheckVnd: 800000,
    subgroups: [
      { slug: 'sea-tours',   name: { ru: 'Морские', en: 'Sea Tours', vi: 'Tour biển' } },
      { slug: 'mountain',    name: { ru: 'Горные', en: 'Mountain', vi: 'Tour núi' } },
      { slug: 'gastro',      name: { ru: 'Гастро', en: 'Gastro', vi: 'Ẩm thực' } },
      { slug: 'vip',         name: { ru: 'VIP', en: 'VIP', vi: 'VIP' } },
      { slug: 'diving',      name: { ru: 'Дайвинг', en: 'Diving', vi: 'Lặn biển' } },
      { slug: 'snorkeling',  name: { ru: 'Снорклинг', en: 'Snorkeling', vi: 'Lặn ống thở' } },
      { slug: 'surfing',     name: { ru: 'Сёрфинг', en: 'Surfing', vi: 'Lướt sóng' } },
    ],
  },
  {
    id: 5,
    slug: 'spa',
    emoji: '💆',
    name: { ru: 'Спа', en: 'Spa', vi: 'Spa' },
    commissionPct: 6,
    userDiscountPct: 5,
    bloggerReferralPct: 3,
    avgCheckVnd: 400000,
    subgroups: [
      { slug: 'thai',    name: { ru: 'Тайский', en: 'Thai', vi: 'Massage Thái' } },
      { slug: 'vietnam', name: { ru: 'Вьетнамский', en: 'Vietnamese', vi: 'Massage Việt' } },
      { slug: 'premium', name: { ru: 'Премиум', en: 'Premium', vi: 'Cao cấp' } },
      { slug: 'home',    name: { ru: 'На дому', en: 'Home', vi: 'Tại nhà' } },
      { slug: 'sauna',   name: { ru: 'Сауна', en: 'Sauna', vi: 'Sauna' } },
      { slug: 'springs', name: { ru: 'Источники', en: 'Springs', vi: 'Suối nước nóng' } },
    ],
  },
  {
    id: 6,
    slug: 'sports',
    emoji: '🏋️',
    name: { ru: 'Спорт', en: 'Sports', vi: 'Thể thao' },
    commissionPct: 5,
    userDiscountPct: 4,
    bloggerReferralPct: 3,
    avgCheckVnd: 500000,
    subgroups: [
      { slug: 'gyms',        name: { ru: 'Залы', en: 'Gyms', vi: 'Phòng gym' } },
      { slug: 'yoga',        name: { ru: 'Йога', en: 'Yoga', vi: 'Yoga' } },
      { slug: 'pools',       name: { ru: 'Бассейны', en: 'Swimming Pools', vi: 'Bể bơi' } },
      { slug: 'martial',     name: { ru: 'Единоборства', en: 'Martial Arts', vi: 'Võ thuật' } },
      { slug: 'tennis',      name: { ru: 'Теннис', en: 'Tennis', vi: 'Tennis' } },
      { slug: 'surf-school', name: { ru: 'Сёрфинг', en: 'Surfing', vi: 'Lướt sóng' } },
      { slug: 'crossfit',    name: { ru: 'Кроссфит', en: 'Crossfit', vi: 'Crossfit' } },
    ],
  },
  {
    id: 7,
    slug: 'medicine',
    emoji: '🏥',
    name: { ru: 'Медицина', en: 'Medicine', vi: 'Y tế' },
    commissionPct: 3,
    userDiscountPct: 2,
    bloggerReferralPct: 2,
    avgCheckVnd: 1000000,
    subgroups: [
      { slug: 'clinics',      name: { ru: 'Клиники', en: 'Clinics', vi: 'Phòng khám' } },
      { slug: 'dental',       name: { ru: 'Стоматология', en: 'Dental', vi: 'Nha khoa' } },
      { slug: 'labs',         name: { ru: 'Анализы', en: 'Labs', vi: 'Xét nghiệm' } },
      { slug: 'pharmacy',     name: { ru: 'Аптеки', en: 'Pharmacy', vi: 'Nhà thuốc' } },
      { slug: 'traditional',  name: { ru: 'Трад. медицина', en: 'Traditional', vi: 'Y học cổ truyền' } },
      { slug: 'vaccination',  name: { ru: 'Вакцинация', en: 'Vaccination', vi: 'Tiêm chủng' } },
    ],
  },
  {
    id: 8,
    slug: 'education',
    emoji: '📚',
    name: { ru: 'Образование', en: 'Education', vi: 'Giáo dục' },
    commissionPct: 5,
    userDiscountPct: 4,
    bloggerReferralPct: 3,
    avgCheckVnd: 500000,
    subgroups: [
      { slug: 'languages', name: { ru: 'Языки', en: 'Languages', vi: 'Ngôn ngữ' } },
      { slug: 'tutors',    name: { ru: 'Репетиторы', en: 'Tutors', vi: 'Gia sư' } },
      { slug: 'it',        name: { ru: 'IT-курсы', en: 'IT Courses', vi: 'Khóa học IT' } },
      { slug: 'kids',      name: { ru: 'Дети', en: 'Kids', vi: 'Trẻ em' } },
      { slug: 'music',     name: { ru: 'Музыка', en: 'Music', vi: 'Âm nhạc' } },
      { slug: 'dance',     name: { ru: 'Танцы', en: 'Dance', vi: 'Khiêu vũ' } },
    ],
  },
  {
    id: 9,
    slug: 'shopping',
    emoji: '🛍',
    name: { ru: 'Шоппинг', en: 'Shopping', vi: 'Mua sắm' },
    commissionPct: 7,
    userDiscountPct: 5,
    bloggerReferralPct: 4,
    avgCheckVnd: 300000,
    subgroups: [
      { slug: 'clothes',     name: { ru: 'Одежда', en: 'Clothes', vi: 'Quần áo' } },
      { slug: 'electronics', name: { ru: 'Электроника', en: 'Electronics', vi: 'Điện tử' } },
      { slug: 'souvenirs',   name: { ru: 'Сувениры', en: 'Souvenirs', vi: 'Quà lưu niệm' } },
      { slug: 'markets',     name: { ru: 'Рынки', en: 'Markets', vi: 'Chợ' } },
      { slug: 'jewelry',     name: { ru: 'Ювелирные', en: 'Jewelry', vi: 'Trang sức' } },
      { slug: 'shoes',       name: { ru: 'Обувь', en: 'Shoes', vi: 'Giày dép' } },
      { slug: 'home-goods',  name: { ru: 'Дом', en: 'Home Goods', vi: 'Đồ gia dụng' } },
    ],
  },
  {
    id: 10,
    slug: 'entertainment',
    emoji: '🎉',
    name: { ru: 'Развлечения', en: 'Entertainment', vi: 'Giải trí' },
    commissionPct: 6,
    userDiscountPct: 5,
    bloggerReferralPct: 4,
    avgCheckVnd: 400000,
    subgroups: [
      { slug: 'clubs',     name: { ru: 'Клубы', en: 'Clubs', vi: 'Câu lạc bộ đêm' } },
      { slug: 'karaoke',   name: { ru: 'Караоке', en: 'Karaoke', vi: 'Karaoke' } },
      { slug: 'bowling',   name: { ru: 'Боулинг', en: 'Bowling', vi: 'Bowling' } },
      { slug: 'cinema',    name: { ru: 'Кино', en: 'Cinema', vi: 'Rạp phim' } },
      { slug: 'escape',    name: { ru: 'Квест-комнаты', en: 'Escape Rooms', vi: 'Escape room' } },
      { slug: 'boardgames',name: { ru: 'Настолки', en: 'Board Games', vi: 'Trò chơi bàn' } },
      { slug: 'parks',     name: { ru: 'Парки', en: 'Parks', vi: 'Công viên' } },
    ],
  },
  {
    id: 11,
    slug: 'telecom',
    emoji: '📱',
    name: { ru: 'Связь', en: 'Telecom', vi: 'Viễn thông' },
    commissionPct: 7,
    userDiscountPct: 5,
    bloggerReferralPct: 4,
    avgCheckVnd: 200000,
    subgroups: [
      { slug: 'sim',          name: { ru: 'SIM', en: 'SIM Cards', vi: 'SIM' } },
      { slug: 'wifi',         name: { ru: 'WiFi', en: 'WiFi', vi: 'WiFi' } },
      { slug: 'phone-repair', name: { ru: 'Ремонт телефонов', en: 'Phone Repair', vi: 'Sửa điện thoại' } },
      { slug: 'accessories',  name: { ru: 'Аксессуары', en: 'Accessories', vi: 'Phụ kiện' } },
      { slug: 'laptops',      name: { ru: 'Ноутбуки', en: 'Laptops', vi: 'Laptop' } },
    ],
  },
  {
    id: 12,
    slug: 'household',
    emoji: '🧹',
    name: { ru: 'Быт', en: 'Household', vi: 'Dịch vụ nhà' },
    commissionPct: 6,
    userDiscountPct: 4,
    bloggerReferralPct: 3,
    avgCheckVnd: 300000,
    subgroups: [
      { slug: 'cleaning',   name: { ru: 'Уборка', en: 'Cleaning', vi: 'Dọn dẹp' } },
      { slug: 'laundry',    name: { ru: 'Стирка', en: 'Laundry', vi: 'Giặt ủi' } },
      { slug: 'appliances', name: { ru: 'Ремонт техники', en: 'Appliance Repair', vi: 'Sửa đồ gia dụng' } },
      { slug: 'plumbing',   name: { ru: 'Сантехник', en: 'Plumbing', vi: 'Thợ nước' } },
      { slug: 'electrical', name: { ru: 'Электрик', en: 'Electrical', vi: 'Thợ điện' } },
      { slug: 'ac',         name: { ru: 'Кондиционеры', en: 'AC Service', vi: 'Điều hòa' } },
    ],
  },
  {
    id: 13,
    slug: 'pets',
    emoji: '🐾',
    name: { ru: 'Животные', en: 'Pets', vi: 'Thú cưng' },
    commissionPct: 6,
    userDiscountPct: 4,
    bloggerReferralPct: 3,
    avgCheckVnd: 300000,
    subgroups: [
      { slug: 'vet',       name: { ru: 'Ветеринар', en: 'Vet', vi: 'Thú y' } },
      { slug: 'grooming',  name: { ru: 'Груминг', en: 'Grooming', vi: 'Tắm thú cưng' } },
      { slug: 'boarding',  name: { ru: 'Передержка', en: 'Boarding', vi: 'Gửi thú cưng' } },
      { slug: 'pet-food',  name: { ru: 'Корма', en: 'Pet Food', vi: 'Thức ăn thú cưng' } },
      { slug: 'pet-store', name: { ru: 'Зоомагазин', en: 'Pet Store', vi: 'Cửa hàng thú cưng' } },
    ],
  },
  {
    id: 14,
    slug: 'legal',
    emoji: '⚖️',
    name: { ru: 'Юридические', en: 'Legal', vi: 'Pháp lý' },
    commissionPct: 3,
    userDiscountPct: 2,
    bloggerReferralPct: 2,
    avgCheckVnd: 2000000,
    subgroups: [
      { slug: 'visas',        name: { ru: 'Визы', en: 'Visas', vi: 'Visa' } },
      { slug: 'documents',    name: { ru: 'Документы', en: 'Documents', vi: 'Giấy tờ' } },
      { slug: 'consultation', name: { ru: 'Консультации', en: 'Consultation', vi: 'Tư vấn' } },
      { slug: 'registration', name: { ru: 'Регистрация', en: 'Registration', vi: 'Đăng ký' } },
      { slug: 'taxes',        name: { ru: 'Налоги', en: 'Taxes', vi: 'Thuế' } },
    ],
  },
  {
    id: 15,
    slug: 'business',
    emoji: '💼',
    name: { ru: 'Бизнес', en: 'Business', vi: 'Kinh doanh' },
    commissionPct: 4,
    userDiscountPct: 3,
    bloggerReferralPct: 2,
    avgCheckVnd: 1000000,
    subgroups: [
      { slug: 'accounting',  name: { ru: 'Бухгалтерия', en: 'Accounting', vi: 'Kế toán' } },
      { slug: 'llc',         name: { ru: 'Регистрация ООО', en: 'LLC Registration', vi: 'Đăng ký công ty' } },
      { slug: 'coworking',   name: { ru: 'Коворкинг', en: 'Coworking', vi: 'Coworking' } },
      { slug: 'notary',      name: { ru: 'Нотариус', en: 'Notary', vi: 'Công chứng' } },
      { slug: 'translation', name: { ru: 'Переводчик', en: 'Translator', vi: 'Phiên dịch' } },
    ],
  },
  {
    id: 16,
    slug: 'photo',
    emoji: '📸',
    name: { ru: 'Фото', en: 'Photo', vi: 'Nhiếp ảnh' },
    commissionPct: 5,
    userDiscountPct: 4,
    bloggerReferralPct: 3,
    avgCheckVnd: 500000,
    subgroups: [
      { slug: 'photoshoot', name: { ru: 'Фотосессии', en: 'Photoshoot', vi: 'Chụp ảnh' } },
      { slug: 'video',      name: { ru: 'Видео', en: 'Video', vi: 'Quay phim' } },
      { slug: 'drone',      name: { ru: 'Дрон', en: 'Drone', vi: 'Drone' } },
      { slug: 'editing',    name: { ru: 'Монтаж', en: 'Editing', vi: 'Dựng phim' } },
      { slug: 'id-photo',   name: { ru: 'Фото на документы', en: 'ID Photo', vi: 'Ảnh thẻ' } },
    ],
  },
  {
    id: 17,
    slug: 'repair',
    emoji: '🔧',
    name: { ru: 'Ремонт', en: 'Repair', vi: 'Sửa chữa' },
    commissionPct: 4,
    userDiscountPct: 3,
    bloggerReferralPct: 2,
    avgCheckVnd: 1000000,
    subgroups: [
      { slug: 'apartment', name: { ru: 'Квартиры', en: 'Apartment', vi: 'Sửa nhà' } },
      { slug: 'furniture', name: { ru: 'Мебель', en: 'Furniture', vi: 'Đồ gỗ' } },
      { slug: 'electric',  name: { ru: 'Электрика', en: 'Electrical', vi: 'Điện' } },
      { slug: 'welding',   name: { ru: 'Сварка', en: 'Welding', vi: 'Hàn' } },
      { slug: 'painting',  name: { ru: 'Покраска', en: 'Painting', vi: 'Sơn' } },
    ],
  },
  {
    id: 18,
    slug: 'kids',
    emoji: '👶',
    name: { ru: 'Дети', en: 'Kids', vi: 'Trẻ em' },
    commissionPct: 5,
    userDiscountPct: 4,
    bloggerReferralPct: 3,
    avgCheckVnd: 400000,
    subgroups: [
      { slug: 'nannies',  name: { ru: 'Няни', en: 'Nannies', vi: 'Trông trẻ' } },
      { slug: 'dev',      name: { ru: 'Развивашки', en: 'Development', vi: 'Phát triển trẻ' } },
      { slug: 'nursery',  name: { ru: 'Сады', en: 'Nursery', vi: 'Nhà trẻ' } },
      { slug: 'playroom', name: { ru: 'Игровые', en: 'Playrooms', vi: 'Khu vui chơi' } },
      { slug: 'animator', name: { ru: 'Аниматоры', en: 'Entertainers', vi: 'Diễn viên hề' } },
    ],
  },
  {
    id: 19,
    slug: 'delivery',
    emoji: '🚚',
    name: { ru: 'Доставка', en: 'Delivery', vi: 'Giao hàng' },
    commissionPct: 7,
    userDiscountPct: 5,
    bloggerReferralPct: 4,
    avgCheckVnd: 200000,
    subgroups: [
      { slug: 'couriers', name: { ru: 'Курьеры', en: 'Couriers', vi: 'Giao hàng' } },
      { slug: 'movers',   name: { ru: 'Грузчики', en: 'Movers', vi: 'Chuyển đồ' } },
      { slug: 'parcels',  name: { ru: 'Посылки', en: 'Parcels', vi: 'Bưu kiện' } },
      { slug: 'moving',   name: { ru: 'Переезд', en: 'Moving', vi: 'Dọn nhà' } },
      { slug: 'storage',  name: { ru: 'Хранение', en: 'Storage', vi: 'Lưu kho' } },
    ],
  },
  {
    id: 20,
    slug: 'creative',
    emoji: '🎨',
    name: { ru: 'Творчество', en: 'Creative', vi: 'Nghệ thuật' },
    commissionPct: 6,
    userDiscountPct: 4,
    bloggerReferralPct: 3,
    avgCheckVnd: 300000,
    subgroups: [
      { slug: 'workshops', name: { ru: 'Мастер-классы', en: 'Workshops', vi: 'Xưởng học' } },
      { slug: 'drawing',   name: { ru: 'Рисование', en: 'Drawing', vi: 'Vẽ' } },
      { slug: 'music-cls', name: { ru: 'Музыка', en: 'Music Classes', vi: 'Nhạc' } },
      { slug: 'ceramics',  name: { ru: 'Керамика', en: 'Ceramics', vi: 'Gốm sứ' } },
      { slug: 'cooking',   name: { ru: 'Кулинарные', en: 'Cooking Classes', vi: 'Nấu ăn' } },
    ],
  },
  {
    id: 21,
    slug: 'beauty',
    emoji: '💅',
    name: { ru: 'Бьюти', en: 'Beauty', vi: 'Làm đẹp' },
    commissionPct: 6,
    userDiscountPct: 5,
    bloggerReferralPct: 4,
    avgCheckVnd: 400000,
    subgroups: [
      { slug: 'nails',     name: { ru: 'Ногти', en: 'Nails', vi: 'Làm móng' } },
      { slug: 'haircut',   name: { ru: 'Стрижка', en: 'Haircut', vi: 'Cắt tóc' } },
      { slug: 'coloring',  name: { ru: 'Окрашивание', en: 'Coloring', vi: 'Nhuộm tóc' } },
      { slug: 'lashes',    name: { ru: 'Ресницы', en: 'Lashes', vi: 'Mi' } },
      { slug: 'brows',     name: { ru: 'Брови', en: 'Brows', vi: 'Lông mày' } },
      { slug: 'makeup',    name: { ru: 'Макияж', en: 'Makeup', vi: 'Trang điểm' } },
      { slug: 'barber',    name: { ru: 'Барбер', en: 'Barber', vi: 'Cắt tóc nam' } },
      { slug: 'cosmetol',  name: { ru: 'Косметология', en: 'Cosmetology', vi: 'Thẩm mỹ' } },
      { slug: 'epilation', name: { ru: 'Эпиляция', en: 'Epilation', vi: 'Tẩy lông' } },
      { slug: 'permanent', name: { ru: 'Перманент', en: 'Permanent Makeup', vi: 'Phun xăm' } },
    ],
  },
  {
    id: 22,
    slug: 'other',
    emoji: '🔮',
    name: { ru: 'Другое', en: 'Other', vi: 'Khác' },
    commissionPct: 5,
    userDiscountPct: 4,
    bloggerReferralPct: 3,
    avgCheckVnd: 300000,
    subgroups: [
      { slug: 'astrology',  name: { ru: 'Астрология', en: 'Astrology', vi: 'Chiêm tinh' } },
      { slug: 'translat',   name: { ru: 'Переводы', en: 'Translation', vi: 'Phiên dịch' } },
      { slug: 'concierge',  name: { ru: 'Консьерж', en: 'Concierge', vi: 'Concierge' } },
      { slug: 'assistant',  name: { ru: 'Личный помощник', en: 'Personal Assistant', vi: 'Trợ lý' } },
      { slug: 'unique',     name: { ru: 'Уникальные', en: 'Unique', vi: 'Độc đáo' } },
    ],
  },
]

// Quick lookup by slug
export const VERTICAL_BY_SLUG = Object.fromEntries(
  VERTICALS_CONFIG.map(v => [v.slug, v])
)

// Blogger referral % depends on vertical's average check
export const BLOGGER_REFERRAL_BY_VERTICAL = {
  food: 4, shopping: 4, beauty: 4, entertainment: 4,
  transport: 3, sports: 3, tours: 3, spa: 3,
  housing: 2, legal: 2, medicine: 2,
}
